### ISSUE TITLE
Cert Checklist 2: Self Healing / Automatic Failover

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#29]
- [ ] **2.1 [,R/A]**   : Does your workload support multiple active replicas (same image individually addressable) ?
- [ ] **2.2 [,R/A]**   : Does your workload manage networking topologies that intelligently route requests when recovery/disruption occurs ? 
- [ ] **2.3 [R ,R]**   : Does your workload monitor its health and understand how it reacts to these events ?
- [ ] **2.4 [,P/A]**   : Does your workload monitor support and active/standby failover model and have you made it work in a native Kubernetes method ?

> **{Check #} [{Catalog Min}, {Certified}]** : {Condition}

Key | Action
-- | --
R | Required
A | If Applicable
P | Preferred
'' | Optional
