### ISSUE TITLE
Cert Checklist 4: Ability to scale up/down

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#31]
- [ ] **4.1 [P,R]**   : Does your workload support being manually scaled to add instance transparent to the end user ?
- [ ] **4.2 [,P]**   : Does your workload support horizontal pod autoscaling ?
- [ ] **4.3 [,R/A]**   : Does your workload support scaling a StatefulSet (if using StatefulSets) ? Can you add members into the StatefulSet for a stateful workload without service interruption ?
- [ ] **4.4 [,R/A]**   : Does your workload controlled scale down ?
- [ ] **4.5 [,R/A]**   : Does your workload support being deployed more than once in the same cluster ?

> **{Check #} [{Catalog Min}, {Certified}]** : {Condition}

Key | Action
-- | --
R | Required
A | If Applicable
P | Preferred
'' | Optional
