### ISSUE TITLE
Cert Checklist 5: Production Grade Config and Topology

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#32]
- [ ] **5.1 [R,R]**   : Does your workload manage all image vulnerabilities on an ongoing basis on the timelines established with the Product Security Incident Response Team (PSIRT) ? 
- [ ] **5.2 [R,R]**   : Does your workload ensure integration with the content CICD continuous scanning for vulnerabilities for ongoing visibility of image vulnerabilities ?
- [ ] **5.3 [R,P]**   : Does your workload ensure that if you are shipping images on Docker Hub (or any image repository) that the repository's vulnerability detector does not show critical exposures for your shipped images ?
- [ ] **5.4 [P,R]**   : Does your workload deliver RedHat certified UBI based images ?

> **{Check #} [{Catalog Min}, {Certified}]** : {Condition}

Key | Action
-- | --
R | Required
A | If Applicable
P | Preferred
'' | Optional
