### ISSUE TITLE
Operator 1.0.0 Features

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#33]
The 1.0.0 operator should have the following features at launch:

- [x] Installation and configuration of CSI Plugin.
- [x] Reinitialize the CSI Plugin when changes are made to the spec in the `CSIScaleOperator` Custom Resource.
- [x] Changes to `Secrets` referred to by the `clusters` `secret` field.
- [x] Remote File Systems.
- [x] Node Selectors.
- [X] Namespacing in OpenShift (with SCC) and raw Kubernetes.

---
The `CSIScaleOperator` Custom Resource will have the following specification
```
apiVersion: scale.ibm.com/v1alpha1
kind: 'CSIScaleOperator'
metadata:
    name: 'csi-scale-operator'
status: {}
spec:
  # Optional
  # ----
  # Attacher image for csi (actually attaches to the storage).
  attacher: "quay.io/k8scsi/csi-attacher:v1.0.0"
  
  # Provisioner image for csi (actually issues provision requests).
  provisioner:"quay.io/k8scsi/csi-provisioner:v1.0.0"
  
  # Sidecar container image for the csi spectrum scale plugin pods.
  driverRegistrar: "quay.io/k8scsi/csi-node-driver-registrar:v1.0.1"
  
  # Image name for the csi spectrum scale plugin container.
  spectrumScale: "quay.io/mew2057/ibm-spectrum-scale-csi-driver:v0.9.0"
  # ----
  
  # Required
  # ----
  # The path to the gpfs file system mounted on the host machine.
  scaleHostpath: "/ibm/fs1"

  # A collection of gpfs cluster properties for the csi driver to mount.
  clusters:
    # The cluster id of the gpfs cluster specified (mandatory).
    - id: "2120508922778391120"
      
      # A string specifying a secret resource name.
      secrets: "secret1"
      
      # Require a secure SSL connection to connect to GPFS.
      secureSslMode: false
      
      # A string specifying a cacert resource name.
      # cacert: <>
      
      # The primary file system for the GPFS cluster
      primary:
        # The name of the primary filesystem.
        primaryFS: "fs1"
        # The name of the primary fileset, created in primaryFS.
        primaryFset: "csiFset2"
        
      # A collection of targets for REST calls.
      restApi:
        # The hostname of the REST server.
        - guiHost: "GUI_HOST"
        
          # The port number running the REST server.
          # guiPort
        
  # ----
```

**Comment by mew2057** [comment]
It looks like we're now feature complete for 1.0.0. Working on documentation now.

**Comment by mew2057** [comment]
New feature added in PR  #51:
The operator will now have a default namespace `ibm-spectrum-scale-csi-driver`.
If deploying by hand this is not easily changed, however, OLM based deployments will still have the same ease of use.

**Comment by mew2057** [comment]
Once PR #60 and PR #59 are in this is basically able to be closed.

**Comment by mew2057** [comment]
Closing since we're now at GA
