### ISSUE TITLE
[MDD] Operator 1.0.1 Features

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#61]
# Operator 1.0.1

## Description
The `1.0.1` release of the Spectrum Scale CSI Operator will primarily be targeted to clear the required certification for integration into the [IBM CloudPak](https://www.ibm.com/cloud/paks/).

To achieve this goal the following Features must be implemented:
- [ ] Implement  Liveliness and Readiness probe as outlined in Issue #48
- [ ] Determine resource parameters for operator (driver needs this too) #46 
- [ ] Clear any warnings/errors flagged in cert process.

---

At this time no features are planned for the `1.0.1` release
